blank_issues_enabled: false

contact_links:
  - name: 💬 Perguntas e Discussões
    url: https://github.com/4sllan/IBAV/discussions
    about: Por favor, faça e responda perguntas aqui.

  - name: 🔐 Relatar Vulnerabilidade de Segurança
    url: https://github.com/4sllan/IBAV/security/advisories/new
    about: Por favor, relate vulnerabilidades de segurança em privado.

  - name: 📖 Documentação
    url: https://github.com/4sllan/IBAV/blob/main/docs/docs.md
    about: Consulte a documentação completa do IBAV.