name: 🚀 Solicitação de Funcionalidade
description: Sugira uma nova funcionalidade ou melhoria
title: "[Funcionalidade]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Tem uma ideia para melhorar o IBAV? Incrível 🔥

  - type: dropdown
    id: version
    attributes:
      label: Versão relacionada
      options:
        - MVP
        - Versão 2
        - Versão 3
        - Metodologia
        - Documentação
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Qual área isso impacta?
      options:
        - Cálculo do VJV
        - Cálculo do IVB
        - Interface do usuário
        - Metodologia de avaliação
        - Documentação
        - DX (Experiência do Desenvolvedor)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descreva a funcionalidade
      placeholder: Explique sua ideia claramente.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Qual problema isso resolve?
      placeholder: Por que isso é necessário?
    validations:
      required: true